<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Club;
use App\Enums\ClubCategory;
use Carbon\Carbon;

class ClubsTableSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        Club::insert([
            [
                'name' => 'MMUsic Club',
                'email' => 'mmusic@mmu.edu.my',
                'registration_link' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'registration_open' => false,
                'category' => ClubCategory::ART->value,
                'banner_image' => 'images/1.jpg',
                'profile_picture' => 'images/mmu.png',
                'theme' => 'Default',
                'created_at' => $now,
                'updated_at' => $now,
                'is_Verified' => true,
            ],
            [
                'name' => 'MMU Superheroes',
                'email' => 'superheroes@mmu.edu.my',
                'registration_link' => null,
                'registration_open' => false,
                'category' => ClubCategory::COMMUNITY->value,
                'banner_image' => 'images/2.jpg',
                'profile_picture' => 'images/mmu.png',
                'theme' => 'Default',
                'created_at' => $now,
                'updated_at' => $now,
                'is_Verified' => true,
            ],
            [
                'name' => 'Buddhist Society',
                'email' => 'buddhist_society@mmu.edu.my',
                'registration_link' => null,
                'registration_open' => false,
                'category' => ClubCategory::RELIGION->value,
                'banner_image' => 'images/3.png',
                'profile_picture' => 'images/mmu.png',
                'theme' => 'Default',
                'created_at' => $now,
                'updated_at' => $now,
                'is_Verified' => true,
            ],
            [
                'name' => 'MMU Esports',
                'email' => 'mmuesports@mmu.edu.my',
                'registration_link' => null,
                'registration_open' => false,
                'category' => ClubCategory::ENTERTAINMENT->value,
                'banner_image' => 'images/4.png',
                'profile_picture' => 'images/mmu.png',
                'theme' => 'Default',
                'created_at' => $now,
                'updated_at' => $now,
                'is_Verified' => true,
            ],
            [
                'name' => 'Chinese Language Society',
                'email' => 'chinese_language@mmu.edu.my',
                'registration_link' => null,
                'registration_open' => false,
                'category' => ClubCategory::CULTURAL->value,
                'banner_image' => 'images/5.png',
                'profile_picture' => 'images/mmu.png',
                'theme' => 'Default',
                'created_at' => $now,
                'updated_at' => $now,
                'is_Verified' => true,
            ],
            [
                'name' => 'IT Society',
                'email' => 'itsociety@mmu.edu.my',
                'registration_link' => null,
                'registration_open' => false,
                'category' => ClubCategory::TECH->value,
                'banner_image' => 'images/6.jpg',
                'profile_picture' => 'images/mmu.png',
                'theme' => 'Default',
                'created_at' => $now,
                'updated_at' => $now,
                'is_Verified' => true,
            ],
            [
                'name' => 'Badminton Club',
                'email' => 'badminton@mmu.edu.my',
                'registration_link' => null,
                'registration_open' => false,
                'category' => ClubCategory::RECREATIONAL->value,
                'banner_image' => 'images/7.jpg',
                'profile_picture' => 'images/mmu.png',
                'theme' => 'Default',
                'created_at' => $now,
                'updated_at' => $now,
                'is_Verified' => true,
            ],
            [
                'name' => 'CyberFitness Club',
                'email' => 'cyberfitness@mmu.edu.my',
                'registration_link' => null,
                'registration_open' => false,
                'category' => ClubCategory::RECREATIONAL->value,
                'banner_image' => 'images/8.jpg',
                'profile_picture' => 'images/mmu.png',
                'theme' => 'Default',
                'created_at' => $now,
                'updated_at' => $now,
                'is_Verified' => true,
            ],
            [
                'name' => 'TechGirls MMU',
                'email' => 'techgirls@mmu.edu.my',
                'registration_link' => null,
                'registration_open' => false,
                'category' => ClubCategory::TECH->value,
                'banner_image' => 'images/9.jpg',
                'profile_picture' => 'images/mmu.png',
                'theme' => 'Default',
                'created_at' => $now,
                'updated_at' => $now,
                'is_Verified' => true,
            ],
            [
                'name' => 'Rentak Dance Club',
                'email' => 'rentak_dance@mmu.edu.my',
                'registration_link' => null,
                'registration_open' => false,
                'category' => ClubCategory::ART->value,
                'banner_image' => 'images/10.jpg',
                'profile_picture' => 'images/mmu.png',
                'theme' => 'Default',
                'created_at' => $now,
                'updated_at' => $now,
                'is_Verified' => true,
            ],
            [
                'name' => 'Chess Club',
                'email' => 'chessclub@mmu.edu.my',
                'registration_link' => null,
                'registration_open' => false,
                'category' => ClubCategory::ENTERTAINMENT->value,
                'banner_image' => 'images/11.jpeg',
                'profile_picture' => 'images/mmu.png',
                'theme' => 'Default',
                'created_at' => $now,
                'updated_at' => $now,
                'is_Verified' => true,
            ],
            [
                'name' => 'University Peer Group',
                'email' => 'peer_group@mmu.edu.my',
                'registration_link' => null,
                'registration_open' => false,
                'category' => ClubCategory::COMMUNITY->value,
                'banner_image' => 'images/12.png',
                'profile_picture' => 'images/mmu.png',
                'theme' => 'Default',
                'created_at' => $now,
                'updated_at' => $now,
                'is_Verified' => true,
            ],
            [
                'name' => 'Table Tennis Club',
                'email' => 'tabletennis@mmu.edu.my',
                'registration_link' => null,
                'registration_open' => false,
                'category' => ClubCategory::RECREATIONAL->value,
                'banner_image' => 'images/13.png',
                'profile_picture' => 'images/mmu.png',
                'theme' => 'Default',
                'created_at' => $now,
                'updated_at' => $now,
                'is_Verified' => true,
            ],
        ]);
    }
}